"""生产 H3 应用 workflow_json 测试夹具(2026-09-12 自 core /api/apps 拉取真图)。

覆盖 SamplerCustomAdvanced + KSamplerSelect/BasicScheduler/BasicGuider 三元组链形状
(h3-t2v/h3-i2v/h3-fl2v);加速图转换器单测以此断言改写后每条边类型一致、无字符串入对象槽。
"""

H3_T2V_GRAPH = {'6': {'class_type': 'UNETLoader',
       'inputs': {'unet_name': 'minimax_h3_fl2va_pruned_int8_convrot.safetensors',
                  'weight_dtype': 'default'}},
 '13': {'class_type': 'CLIPLoader',
        'inputs': {'clip_name': 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors',
                   'type': 'minimax',
                   'device': 'default'}},
 '11': {'class_type': 'VAELoader', 'inputs': {'vae_name': 'minimax_h3_video_vae_fp16.safetensors'}},
 '24': {'class_type': 'VAELoader', 'inputs': {'vae_name': 'minimax_h3_audio_vae_fp32.safetensors'}},
 '104': {'class_type': 'MiniMaxH3ImageToVideo',
         'inputs': {'clip': ['13', 0],
                    'vae': ['11', 0],
                    'prompt': '现实主义都市短剧风格，夜晚老式居民楼楼道，昏黄声控灯忽明忽暗，墙面斑驳。一位五十岁的中年女人提着菜篮子，缓缓走上楼梯，在602室门口停下，深吸一口气，抬手又放下。镜头从楼梯下方仰拍，缓慢推近她的背影。\n'
                              '\n'
                              '对白：女人轻声说："妈，我回来了。"屋内传来苍老的声音："门没锁，进来吧。"\n'
                              '\n'
                              '音频：楼道里的脚步回声，远处邻居家电视声，声控灯电流的轻微嗡鸣，女人压抑的呼吸声，最后一声叹息。',
                    'width': 1344,
                    'height': 768,
                    'length': 124}},
 '15': {'class_type': 'RandomNoise', 'inputs': {'noise_seed': 42}},
 '16': {'class_type': 'BasicGuider', 'inputs': {'model': ['6', 0], 'conditioning': ['104', 0]}},
 '17': {'class_type': 'KSamplerSelect', 'inputs': {'sampler_name': 'res_multistep'}},
 '9': {'class_type': 'BasicScheduler',
       'inputs': {'model': ['6', 0], 'scheduler': 'simple', 'steps': 20, 'denoise': 1.0}},
 '14': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['15', 0],
                   'guider': ['16', 0],
                   'sampler': ['17', 0],
                   'sigmas': ['9', 0],
                   'latent_image': ['104', 1]}},
 '10': {'class_type': 'VAEDecode', 'inputs': {'samples': ['14', 0], 'vae': ['11', 0]}},
 '23': {'class_type': 'VAEDecodeAudio', 'inputs': {'samples': ['14', 1], 'vae': ['24', 0]}},
 '91': {'class_type': 'CreateVideo', 'inputs': {'images': ['10', 0], 'audio': ['23', 0], 'fps': 24.0}},
 '92': {'class_type': 'SaveVideo',
        'inputs': {'video': ['91', 0],
                   'filename_prefix': 'h3eval/t2v_768p_5s',
                   'format': 'auto',
                   'codec': 'auto'}}}

H3_I2V_GRAPH = {'6': {'class_type': 'UNETLoader',
       'inputs': {'unet_name': 'minimax_h3_fl2va_pruned_int8_convrot.safetensors',
                  'weight_dtype': 'default'}},
 '13': {'class_type': 'CLIPLoader',
        'inputs': {'clip_name': 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors',
                   'type': 'minimax',
                   'device': 'default'}},
 '11': {'class_type': 'VAELoader', 'inputs': {'vae_name': 'minimax_h3_video_vae_fp16.safetensors'}},
 '24': {'class_type': 'VAELoader', 'inputs': {'vae_name': 'minimax_h3_audio_vae_fp32.safetensors'}},
 '104': {'class_type': 'MiniMaxH3ImageToVideo',
         'inputs': {'clip': ['13', 0],
                    'vae': ['11', 0],
                    'prompt': '紧接首帧画面：602室的防盗门从里面打开，暖黄色的灯光从屋内洒出，照亮楼道。一位白发老人扶着门框出现，中年女人放下菜篮，上前一步拥抱老人。镜头缓慢横移，从楼道视角转到正对门口的平视视角。\n'
                              '\n'
                              '对白：老人说："回来就好，饭还热着。"女人哽咽着说："妈，这些年辛苦你了。"\n'
                              '\n'
                              '音频：防盗门打开的金属声，屋内电饭煲的提示音，电视戏曲声隐约可闻，两人压抑的啜泣声，楼道声控灯熄灭的轻响。',
                    'width': 1344,
                    'height': 768,
                    'length': 124,
                    'first_frame': ['100', 0]}},
 '15': {'class_type': 'RandomNoise', 'inputs': {'noise_seed': 42}},
 '16': {'class_type': 'BasicGuider', 'inputs': {'model': ['6', 0], 'conditioning': ['104', 0]}},
 '17': {'class_type': 'KSamplerSelect', 'inputs': {'sampler_name': 'res_multistep'}},
 '9': {'class_type': 'BasicScheduler',
       'inputs': {'model': ['6', 0], 'scheduler': 'simple', 'steps': 20, 'denoise': 1.0}},
 '14': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['15', 0],
                   'guider': ['16', 0],
                   'sampler': ['17', 0],
                   'sigmas': ['9', 0],
                   'latent_image': ['104', 1]}},
 '10': {'class_type': 'VAEDecode', 'inputs': {'samples': ['14', 0], 'vae': ['11', 0]}},
 '23': {'class_type': 'VAEDecodeAudio', 'inputs': {'samples': ['14', 1], 'vae': ['24', 0]}},
 '91': {'class_type': 'CreateVideo', 'inputs': {'images': ['10', 0], 'audio': ['23', 0], 'fps': 24.0}},
 '92': {'class_type': 'SaveVideo',
        'inputs': {'video': ['91', 0],
                   'filename_prefix': 'h3eval/i2v_768p_5s',
                   'format': 'auto',
                   'codec': 'auto'}},
 '100': {'class_type': 'LoadImage', 'inputs': {'image': 'i2v_first_frame.png'}}}

H3_FL2V_GRAPH = {'6': {'class_type': 'UNETLoader',
       'inputs': {'unet_name': 'minimax_h3_fl2va_pruned_int8_convrot.safetensors',
                  'weight_dtype': 'default'}},
 '13': {'class_type': 'CLIPLoader',
        'inputs': {'clip_name': 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors',
                   'type': 'minimax',
                   'device': 'default'}},
 '11': {'class_type': 'VAELoader', 'inputs': {'vae_name': 'minimax_h3_video_vae_fp16.safetensors'}},
 '24': {'class_type': 'VAELoader', 'inputs': {'vae_name': 'minimax_h3_audio_vae_fp32.safetensors'}},
 '104': {'class_type': 'MiniMaxH3ImageToVideo',
         'inputs': {'clip': ['13', 0],
                    'vae': ['11', 0],
                    'prompt': '',
                    'width': 1344,
                    'height': 768,
                    'length': 124,
                    'first_frame': ['100', 0],
                    'last_frame': ['101', 0]}},
 '15': {'class_type': 'RandomNoise', 'inputs': {'noise_seed': 8569071399021563701}},
 '16': {'class_type': 'BasicGuider', 'inputs': {'model': ['6', 0], 'conditioning': ['104', 0]}},
 '17': {'class_type': 'KSamplerSelect', 'inputs': {'sampler_name': 'res_multistep'}},
 '9': {'class_type': 'BasicScheduler',
       'inputs': {'model': ['6', 0], 'scheduler': 'simple', 'steps': 20, 'denoise': 1.0}},
 '14': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['15', 0],
                   'guider': ['16', 0],
                   'sampler': ['17', 0],
                   'sigmas': ['9', 0],
                   'latent_image': ['104', 1]}},
 '10': {'class_type': 'VAEDecode', 'inputs': {'samples': ['14', 0], 'vae': ['11', 0]}},
 '23': {'class_type': 'VAEDecodeAudio', 'inputs': {'samples': ['14', 1], 'vae': ['24', 0]}},
 '91': {'class_type': 'CreateVideo', 'inputs': {'images': ['10', 0], 'audio': ['23', 0], 'fps': 24.0}},
 '92': {'class_type': 'SaveVideo',
        'inputs': {'video': ['91', 0], 'filename_prefix': 'ToIV_h3/i2v', 'format': 'auto', 'codec': 'auto'}},
 '100': {'class_type': 'LoadImage', 'inputs': {'image': 'first.png'}},
 '101': {'class_type': 'LoadImage', 'inputs': {'image': 'last.png'}}}

