[Service]
Environment=CUDA_HOME=/home/merlin/ComfyUI-h3-eval/venv/lib/python3.12/site-packages/nvidia/cu13
Environment=CUDA_PATH=/home/merlin/ComfyUI-h3-eval/venv/lib/python3.12/site-packages/nvidia/cu13
Environment=PATH=/home/merlin/ComfyUI-h3-eval/venv/lib/python3.12/site-packages/nvidia/cu13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
