h3_nas:
  base_path: /home/merlin/nas_mount/toiv/comfyui-models/h3/
  diffusion_models: diffusion_models
  text_encoders: text_encoders
  vae: vae
  loras: loras
  latent_upscale_models: latent_upscale_models
