serverAddr = "43.119.32.180"
serverPort = 7001
transport.protocol = "kcp"
loginFailExit = false
auth.method = "token"
auth.token = "token123456"

[[proxies]]
name = "toiv-api"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8090
remotePort = 18090

[[proxies]]
name = "toiv-web"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3100
remotePort = 13100
