"""ToIV LoRA 训练 agent —— 部署在 GPU 机(.100)上，HTTP 服务监听 :9100。

架构: API(CPU 容器)通过 HTTP 调本 agent(同 ComfyUI/TTS/LLM 的访问模式)。
训练后端: AI-Toolkit(ostris)支持 FLUX.2/Qwen-Image/Z-Image/SDXL。
打标后端: Florence2(自动生成 .txt 标签文件)。

接口:
  POST /caption           — Florence2 自动打标
  POST /train             — 启动训练
  GET  /train/{id}/events — SSE 训练进度(step/loss)
  POST /train/{id}/stop   — 停止训练
  GET  /health            — 健康检查

依赖: toiv-trainer venv(含 torch + ai-toolkit requirements + florence2)
启动: F:\\toiv-trainer\\.venv\\Scripts\\python.exe toiv-trainer.py
"""
from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("toiv-trainer")

# ---------------------------------------------------------------------------
# 路径常量(本地 F: 盘,NAS SMB 恢复后可改回 NAS 路径)
# ---------------------------------------------------------------------------
MODELS_ROOT = r"F:\ComfyUIModel\models"
DATASETS_DIR = r"F:\toiv-trainer\datasets"
LORAS_DIR = os.path.join(MODELS_ROOT, "loras")
CHECKPOINTS_DIR = os.path.join(MODELS_ROOT, "checkpoints")
AI_TOOLKIT_DIR = r"F:\toiv-trainer\ai-toolkit"
TRAINER_VENV_PYTHON = r"F:\toiv-trainer\.venv\Scripts\python.exe"
HOST = "0.0.0.0"
PORT = 9100

# ---------------------------------------------------------------------------
# 训练作业管理(内存态,单进程并发训练)
# ---------------------------------------------------------------------------
_jobs: dict[str, dict] = {}  # {trainer_job_id: {proc, status, progress, ...}}
_lock = threading.Lock()


def _resolve_dataset_path(dataset_dir: str) -> str:
    """dataset_dir = job_id → 本地数据集目录。"""
    return os.path.join(DATASETS_DIR, dataset_dir)


def _resolve_ckpt_path(base_ckpt: str) -> str:
    """底模文件名 → 本地 checkpoints 全路径。"""
    return os.path.join(CHECKPOINTS_DIR, base_ckpt)


def _make_ai_toolkit_config(params: dict) -> str:
    """根据训练参数生成 AI-Toolkit 的 YAML 配置文件路径。

    AI-Toolkit 用 YAML 配置驱动训练,不同模型族用不同 config 模板。
    这里按 family 生成最小可用配置。
    """
    family = params.get("family", "flux2")
    job_id = params["job_id"]
    lora_name = params.get("lora_name", f"lora_{job_id[:8]}")
    dataset_path = _resolve_dataset_path(params["dataset_dir"])
    ckpt_path = _resolve_ckpt_path(params["base_ckpt"])
    output_dir = os.path.join(LORAS_DIR, lora_name)
    os.makedirs(output_dir, exist_ok=True)

    # 按模型族选配置模板
    if family in ("flux2", "flux1", "klein"):
        model_key = "flux2-dev" if family == "flux2" else "flux1-dev"
        if family == "klein":
            model_key = "flux2-klein"
        config = f"""# Auto-generated by ToIV trainer for {lora_name}
job: extension
config:
  name: "{lora_name}"
  process:
    - type: sd_trainer
      training_folder: "{output_dir}"
      device: cuda:{params['cuda_device']}
      trigger_word: "{params.get('trigger_words', '')}"
      network:
        type: lora
        linear: {params['network_dim']}
        linear_alpha: {params['network_alpha']}
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 4
      datasets:
        - folder_path: "{dataset_path}"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [{params['resolution']}]
      train:
        batch_size: {params['batch_size']}
        steps: {params['steps']}
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false
        content_or_style: balanced
        gradient_cliping: 1.0
        noise_scheduler: flowmatch
        optimizer: adamw8bit
        lr: {params['lr']}
        dtype: bf16
      model:
        name_or_path: "{ckpt_path}"
        is_flux: true
        arch: {model_key}
        quantize: false
"""
    elif family in ("qwen", "z_image"):
        arch = "qwen-image" if family == "qwen" else "z-image"
        config = f"""# Auto-generated by ToIV trainer for {lora_name}
job: extension
config:
  name: "{lora_name}"
  process:
    - type: sd_trainer
      training_folder: "{output_dir}"
      device: cuda:{params['cuda_device']}
      trigger_word: "{params.get('trigger_words', '')}"
      network:
        type: lora
        linear: {params['network_dim']}
        linear_alpha: {params['network_alpha']}
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 4
      datasets:
        - folder_path: "{dataset_path}"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [{params['resolution']}]
      train:
        batch_size: {params['batch_size']}
        steps: {params['steps']}
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false
        gradient_cliping: 1.0
        optimizer: adamw8bit
        lr: {params['lr']}
        dtype: bf16
      model:
        name_or_path: "{ckpt_path}"
        arch: {arch}
        quantize: false
"""
    else:  # sdxl 等走通用模板
        config = f"""# Auto-generated by ToIV trainer for {lora_name}
job: extension
config:
  name: "{lora_name}"
  process:
    - type: sd_trainer
      training_folder: "{output_dir}"
      device: cuda:{params['cuda_device']}
      trigger_word: "{params.get('trigger_words', '')}"
      network:
        type: lora
        linear: {params['network_dim']}
        linear_alpha: {params['network_alpha']}
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 4
      datasets:
        - folder_path: "{dataset_path}"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [{params['resolution']}]
      train:
        batch_size: {params['batch_size']}
        steps: {params['steps']}
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false
        gradient_cliping: 1.0
        optimizer: adamw8bit
        lr: {params['lr']}
        dtype: bf16
      model:
        name_or_path: "{ckpt_path}"
        is_sdxl: true
        quantize: false
"""
    config_path = os.path.join(output_dir, f"{lora_name}.yaml")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config)
    return config_path


# ---------------------------------------------------------------------------
# 训练进程 stdout 解析(提取 step/loss)
# ---------------------------------------------------------------------------
_STEP_RE = re.compile(r"step[:\s]*(\d+)\s*/\s*(\d+)", re.IGNORECASE)
_LOSS_RE = re.compile(r"loss[:\s]*([\d.]+)", re.IGNORECASE)


def _parse_train_output(line: str, job: dict) -> None:
    """解析 AI-Toolkit stdout,提取 step/loss,更新 job['progress']。"""
    step_m = _STEP_RE.search(line)
    loss_m = _LOSS_RE.search(line)
    if step_m:
        job["progress"]["step"] = int(step_m.group(1))
        job["progress"]["total"] = int(step_m.group(2))
    if loss_m:
        loss = float(loss_m.group(1))
        job["progress"]["loss"] = loss
        job["progress"]["recent_losses"].append(loss)
        if len(job["progress"]["recent_losses"]) > 50:
            job["progress"]["recent_losses"] = job["progress"]["recent_losses"][-50:]


def _monitor_training(trainer_job_id: str, proc: subprocess.Popen, config_path: str, lora_name: str) -> None:
    """后台线程:读训练 stdout,更新进度,训练完标记 done。"""
    job = _jobs[trainer_job_id]
    output_dir = os.path.join(LORAS_DIR, lora_name)
    try:
        for line in iter(proc.stdout.readline, ""):
            line = line.strip()
            if not line:
                continue
            logger.info("[train %s] %s", trainer_job_id[:8], line)
            with _lock:
                _parse_train_output(line, job)
        proc.wait()
        if proc.returncode == 0:
            # 找最新的 .safetensors 文件
            lora_file = ""
            if os.path.isdir(output_dir):
                files = sorted(
                    (f for f in os.listdir(output_dir) if f.endswith(".safetensors")),
                    key=lambda f: os.path.getmtime(os.path.join(output_dir, f)),
                    reverse=True,
                )
                if files:
                    lora_file = os.path.join(output_dir, files[0])
            with _lock:
                job["status"] = "done"
                job["lora_path"] = lora_file
                job["samples"] = []
            logger.info("[train %s] DONE: %s", trainer_job_id[:8], lora_file)
        else:
            with _lock:
                job["status"] = "error"
                job["error"] = f"进程退出码 {proc.returncode}"
            logger.error("[train %s] ERROR: exit %s", trainer_job_id[:8], proc.returncode)
    except Exception as e:
        with _lock:
            job["status"] = "error"
            job["error"] = str(e)
        logger.exception("[train %s] exception", trainer_job_id[:8])


# ---------------------------------------------------------------------------
# Florence2 打标
# ---------------------------------------------------------------------------
def _run_caption(dataset_path: str, cuda_device: int, trigger_words: str) -> list[dict]:
    """用 Florence2 给数据集目录里所有图片打标,生成同名 .txt 文件。"""
    from transformers import AutoProcessor, AutoModelForCausalLM  # type: ignore
    import torch

    model_id = "microsoft/Florence-2-large-ft"
    try:
        processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
        model = AutoModelForCausalLM.from_pretrained(
            model_id, trust_remote_code=True, torch_dtype=torch.float16
        ).to(f"cuda:{cuda_device}").eval()
    except Exception:
        # 回落到 base 模型(如果 ft 版下载失败)
        model_id = "microsoft/Florence-2-base"
        processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
        model = AutoModelForCausalLM.from_pretrained(
            model_id, trust_remote_code=True, torch_dtype=torch.float16
        ).to(f"cuda:{cuda_device}").eval()

    from PIL import Image
    captions = []
    exts = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}
    for fname in sorted(os.listdir(dataset_path)):
        if Path(fname).suffix.lower() not in exts:
            continue
        fpath = os.path.join(dataset_path, fname)
        try:
            image = Image.open(fpath).convert("RGB")
            inputs = processor(images=image, text="<MORE_DETAILED_CAPTION>", return_tensors="pt").to(
                f"cuda:{cuda_device}", torch.float16
            )
            generated = model.generate(
                input_ids=inputs["input_ids"],
                pixel_values=inputs["pixel_values"],
                max_new_tokens=1024,
                num_beams=3,
                do_sample=False,
            )
            text = processor.batch_decode(generated, skip_special_tokens=True)[0]
            # 前置触发词
            if trigger_words:
                text = f"{trigger_words}, {text}"
            txt_path = os.path.splitext(fpath)[0] + ".txt"
            with open(txt_path, "w", encoding="utf-8") as f:
                f.write(text)
            captions.append({"filename": fname, "caption": text})
        except Exception as e:
            logger.warning("打标失败 %s: %s", fname, e)
            captions.append({"filename": fname, "caption": "", "error": str(e)})
    return captions


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------
class TrainerHandler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        logger.info("%s - %s", self.address_string(), fmt % args)

    def _json(self, code: int, data: dict) -> None:
        body = json.dumps(data).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_body(self) -> dict:
        length = int(self.headers.get("Content-Length", 0))
        if length == 0:
            return {}
        raw = self.rfile.read(length)
        return json.loads(raw)

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/health":
            self._json(200, {"ok": True, "jobs": len(_jobs)})
            return

        # SSE: /train/{id}/events
        m = re.match(r"^/train/([^/]+)/events$", path)
        if m:
            self._sse_events(m.group(1))
            return

        self._json(404, {"error": "not found"})

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/caption":
            self._handle_caption()
            return

        if path == "/upload":
            self._handle_upload()
            return

        if path == "/train":
            self._handle_train()
            return

        m = re.match(r"^/train/([^/]+)/stop$", path)
        if m:
            self._handle_stop(m.group(1))
            return

        self._json(404, {"error": "not found"})

    # -- /upload (API 通过 HTTP multipart 传数据集图片,trainer 存本地) --
    def _handle_upload(self) -> None:
        import cgi
        form = cgi.FieldStorage(
            fp=self.rfile,
            headers=self.headers,
            environ={"REQUEST_METHOD": "POST", "CONTENT_TYPE": self.headers.get("Content-Type", "")},
        )
        job_id = form.getvalue("job_id", str(uuid.uuid4())[:8])
        dst_dir = os.path.join(DATASETS_DIR, job_id)
        os.makedirs(dst_dir, exist_ok=True)
        count = 0
        for item in form.list:
            if item.filename:
                ext = os.path.splitext(item.filename)[1].lower() or ".png"
                fname = f"img-{count:03d}{ext}"
                with open(os.path.join(dst_dir, fname), "wb") as f:
                    f.write(item.file.read())
                count += 1
        logger.info("[upload] job_id=%s count=%d", job_id, count)
        self._json(200, {"job_id": job_id, "count": count, "dataset_dir": job_id})

    # -- /caption --
    def _handle_caption(self) -> None:
        body = self._read_body()
        dataset_dir = body.get("dataset_dir", "")
        cuda_device = body.get("cuda_device", 0)
        trigger_words = body.get("trigger_words", "")
        if not dataset_dir:
            self._json(400, {"error": "dataset_dir required"})
            return
        dataset_path = _resolve_dataset_path(dataset_dir)
        if not os.path.isdir(dataset_path):
            self._json(404, {"error": f"数据集目录不存在: {dataset_path}"})
            return
        try:
            captions = _run_caption(dataset_path, cuda_device, trigger_words)
            self._json(200, {"count": len(captions), "captions": captions})
        except Exception as e:
            logger.exception("打标失败")
            self._json(500, {"error": str(e)})

    # -- /train --
    def _handle_train(self) -> None:
        body = self._read_body()
        job_id = body.get("job_id", "")
        if not job_id:
            self._json(400, {"error": "job_id required"})
            return
        trainer_job_id = str(uuid.uuid4())[:8]
        config_path = _make_ai_toolkit_config(body)
        lora_name = body.get("lora_name", f"lora_{job_id[:8]}")

        # 启动 AI-Toolkit 训练进程
        env = os.environ.copy()
        env["CUDA_VISIBLE_DEVICES"] = str(body.get("cuda_device", 0))
        # AI-Toolkit 的 run.py 接 --config 参数
        cmd = [TRAINER_VENV_PYTHON, os.path.join(AI_TOOLKIT_DIR, "run.py"), "--config", config_path]
        logger.info("[train %s] starting: %s", trainer_job_id, " ".join(cmd))
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            cwd=AI_TOOLKIT_DIR,
            env=env,
        )

        with _lock:
            _jobs[trainer_job_id] = {
                "proc": proc,
                "status": "training",
                "progress": {"step": 0, "total": body.get("steps", 1000), "loss": 0, "recent_losses": []},
                "lora_path": "",
                "samples": [],
                "error": "",
                "lora_name": lora_name,
                "config_path": config_path,
            }

        # 后台线程读 stdout 更新进度
        t = threading.Thread(target=_monitor_training, args=(trainer_job_id, proc, config_path, lora_name), daemon=True)
        t.start()

        self._json(200, {"trainer_job_id": trainer_job_id})

    # -- /train/{id}/stop --
    def _handle_stop(self, trainer_job_id: str) -> None:
        with _lock:
            job = _jobs.get(trainer_job_id)
            if not job:
                self._json(404, {"error": "作业不存在"})
                return
            if job["proc"].poll() is None:
                job["proc"].terminate()
            job["status"] = "error"
            job["error"] = "用户停止"
        self._json(200, {"ok": True})

    # -- SSE /train/{id}/events --
    def _sse_events(self, trainer_job_id: str) -> None:
        job = _jobs.get(trainer_job_id)
        if not job:
            self._json(404, {"error": "作业不存在"})
            return

        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "keep-alive")
        self.end_headers()

        last_step = -1
        while True:
            with _lock:
                j = _jobs.get(trainer_job_id)
                if not j:
                    break
                status = j["status"]
                progress = dict(j["progress"])
                lora_path = j.get("lora_path", "")
                error = j.get("error", "")
                samples = j.get("samples", [])

            if progress["step"] != last_step or status in ("done", "error"):
                last_step = progress["step"]
                if status == "training":
                    data = {"event": "progress", **progress}
                elif status == "done":
                    data = {"event": "done", "lora_path": lora_path, "samples": samples}
                else:
                    data = {"event": "error", "message": error or "训练失败"}
                self.wfile.write(f"data: {json.dumps(data)}\n\n")
                self.wfile.flush()

            if status in ("done", "error"):
                break
            time.sleep(1.0)


def main() -> None:
    os.makedirs(DATASETS_DIR, exist_ok=True)
    os.makedirs(LORAS_DIR, exist_ok=True)
    server = ThreadingHTTPServer((HOST, PORT), TrainerHandler)
    logger.info("ToIV Trainer agent listening on %s:%d", HOST, PORT)
    logger.info("AI-Toolkit: %s", AI_TOOLKIT_DIR)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logger.info("Shutting down...")
        server.shutdown()


if __name__ == "__main__":
    main()
