package assistantturns

import "strings"

// NormalizeTurnID accepts only lowercase hex identifiers generated by this
// process. Path fragments from callers never become file or row keys.
func NormalizeTurnID(turnID string) string {
	trimmed := strings.TrimSpace(turnID)
	if trimmed == "" || len(trimmed) > 64 {
		return ""
	}
	for _, r := range trimmed {
		if (r >= '0' && r <= '9') || (r >= 'a' && r <= 'f') {
			continue
		}
		return ""
	}
	return trimmed
}

// ValidTurnID reports whether the identifier shape could have been generated
// here. Ownership still requires reading the round and checking user/canvas.
func ValidTurnID(turnID string) bool {
	return NormalizeTurnID(turnID) != ""
}

func requireActor(userID, canvasID string) error {
	if strings.TrimSpace(userID) == "" || strings.TrimSpace(canvasID) == "" {
		return &Error{Reason: ReasonIdentity, Message: "助手回合需要用户和画布身份"}
	}
	return nil
}
