import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

const libraryPage = readFileSync(new URL("../src/pages/canvas/index.tsx", import.meta.url), "utf8");
const card = readFileSync(new URL("../src/components/canvas/canvas-folder-card.tsx", import.meta.url), "utf8");
const recycleBin = readFileSync(new URL("../src/components/canvas/recycle-bin-dialog.tsx", import.meta.url), "utf8");
const exportService = readFileSync(new URL("../src/lib/canvas/canvas-export.ts", import.meta.url), "utf8");
const exportTypes = readFileSync(new URL("../src/types/canvas-export.ts", import.meta.url), "utf8");
const restoreService = readFileSync(new URL("../src/lib/canvas/canvas-archive-restore.ts", import.meta.url), "utf8");
const deleteDialog = readFileSync(new URL("../src/components/canvas/canvas-delete-projects-dialog.tsx", import.meta.url), "utf8");
const lifecycle = readFileSync(new URL("../src/pages/canvas/use-canvas-project-lifecycle.ts", import.meta.url), "utf8");
const projectRepository = readFileSync(new URL("../src/services/workspace-project-repository.ts", import.meta.url), "utf8");

test("local project library exposes the complete local workspace lifecycle", () => {
    expect(libraryPage).toContain("useCanvasStore");
    expect(libraryPage).toContain("createLocalCanvasProject");
    expect(libraryPage).not.toContain("createCanvasProjectWithRemoteSync");
    expect(libraryPage).toContain("新建文件夹");
    expect(libraryPage).toContain("回收站");
    expect(libraryPage).toContain("导入");
    expect(libraryPage).toContain("exportCanvasProjects");
    expect(libraryPage).toContain("搜索项目");
    expect(libraryPage).toContain('createCanvasLibraryFolder("未命名文件夹")');
    expect(libraryPage).toContain('title="重命名文件夹"');
    expect(libraryPage).not.toContain('title={editingFolderId ? "重命名文件夹" : "新建文件夹"}');
    expect(libraryPage).toContain('const visibleFolders = folderFilter === "all" ? folders : [];');
    expect(libraryPage).not.toContain("window.prompt(\"文件夹名称\"");
    expect(card).toContain("重命名");
    expect(card).toContain("移动至文件夹");
    expect(card).toContain("创建副本");
    expect(card).toContain("删除");
    expect(recycleBin).toContain("恢复到项目列表");
    expect(recycleBin).toContain("isLocalWorkspaceMode()");
    expect(recycleBin).not.toContain('import.meta.env.VITE_CANVAS_LOCAL_MODE !== "false"');
    expect(exportService).toContain("folders?: CanvasFolder[]");
    expect(exportService).toContain("projectFolderIds");
    expect(libraryPage).toContain("restoreCanvasArchive(file");
    expect(restoreService).toContain("folderIdMap");
    expect(restoreService).toContain("data.folders || []");
    expect(exportTypes).toContain("CanvasFolder & { coverPath?: string");
    expect(deleteDialog).not.toContain('import.meta.env.VITE_CANVAS_LOCAL_MODE !== "false"');
    expect(deleteDialog).toContain("deleteWorkspaceCanvasProjects");
    expect(lifecycle).toContain("createWorkspaceCanvasProject");
    expect(lifecycle).toContain("deleteWorkspaceCanvasProjects");
    expect(projectRepository).toContain("isLocalWorkspaceMode()");
    expect(projectRepository).toContain("createLocalCanvasProject");
    expect(projectRepository).toContain("createCanvasProjectWithRemoteSync");
    expect(projectRepository).toContain("deleteLocalCanvasProjects");
    expect(projectRepository).toContain("deleteCanvasProjectsWithRemoteSync");
});
